### ISSUE TITLE
Leap second information

### ISSUE THREAD

**Issue by jodastephen** [ThreeTen/threeten#197]
The TZDB file also contains leap-second information as this information is also supplied by the TZDB maintainers. We should add a single method on the time-zone provider to make this information available to users (even if leap seconds are discontinued, the information is of historical interest). Alternatively, we should remove the information from the file.

**Comment by mirabilos** [comment]
This makes both Joda-Time and JSR 310 unusable for any serious application; thankfully, with [Time4J](https://github.com/MenoData/Time4J) I’ve found a willing replacement.

**Comment by jodastephen** [comment]
See [ThreeTen-Extra](http://www.threeten.org/threeten-extra/) which includes classes that provide [leap second support](https://github.com/ThreeTen/threeten-extra/tree/master/src/main/java/org/threeten/extra/scale) on top of Java 8.
