### ISSUE TITLE
DayOfWeek.format(...) and DayOfWeek.parse(...)

### ISSUE THREAD

**Issue by ge0ffrey** [ThreeTen/threeten#354]
To persist employee rostering patterns and antipatterns, such as persisting that any nurse working Saturday, Sunday and Monday in a row is a bad thing, it would be useful to read and write DayOfWeek instances, to format and parse them.

Is this the right issue tracker to ask for JSR-310 improvements for JDK 9?

**Comment by RogerRiggs** [comment]
DayOfWeek is an enum and has stable printable names and ordinals.
Most of the java.time types have parse and format methods and for consistency
they might be useful on DayOfWeek.

An enhancement in the JDK can be requested via: http://bugreport.java.com/.

**Comment by jodastephen** [comment]
Its a possible enhancement to the JDK, but should be requested there.

Closing this issue here.
